alias: Varmepumpe dag/natt senkning
description: ""
triggers:
  - trigger: time
    at: "00:00:00"
    id: midnight
  - trigger: time
    at: "06:00:00"
    id: morning
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - midnight
          - alias: "Months March to September "
            condition: template
            value_template: "{{ now().month in [3, 4, 5, 6, 7, 8, 9] }}"
        sequence:
          - device_id: 0168cb9e6628e4333a2aa02dcceb2659
            domain: climate
            entity_id: 939fec7cc6847c021ddb0e9af9cf37bc
            type: set_hvac_mode
            hvac_mode: heat
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: 18
            target:
              device_id: 0168cb9e6628e4333a2aa02dcceb2659
        alias: Midnight (summer)
      - conditions:
          - condition: trigger
            id:
              - midnight
          - alias: "Months October to February "
            condition: template
            value_template: "{{ now().month in [10, 11, 12, 1, 2] }}"
        sequence:
          - device_id: 0168cb9e6628e4333a2aa02dcceb2659
            domain: climate
            entity_id: 939fec7cc6847c021ddb0e9af9cf37bc
            type: set_hvac_mode
            hvac_mode: heat
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: 19
            target:
              device_id: 0168cb9e6628e4333a2aa02dcceb2659
        alias: Midnight (winter)
      - conditions:
          - condition: trigger
            id:
              - morning
          - condition: template
            value_template: "{{ now().month in [3, 4, 5, 6, 7, 8, 9] }}"
            alias: "Months March to September "
        sequence:
          - device_id: 0168cb9e6628e4333a2aa02dcceb2659
            domain: climate
            entity_id: 939fec7cc6847c021ddb0e9af9cf37bc
            type: set_hvac_mode
            hvac_mode: fan_only
        alias: Morning (summer)
      - conditions:
          - condition: trigger
            id:
              - morning
          - alias: "Months October to February "
            condition: template
            value_template: "{{ now().month in [10, 11, 12, 1, 2] }}"
        sequence:
          - device_id: 0168cb9e6628e4333a2aa02dcceb2659
            domain: climate
            entity_id: 939fec7cc6847c021ddb0e9af9cf37bc
            type: set_hvac_mode
            hvac_mode: heat
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - action: climate.set_temperature
            metadata: {}
            data:
              temperature: 21
            target:
              device_id: 0168cb9e6628e4333a2aa02dcceb2659
        alias: Morning (winter)
mode: single
