alias: Vaskerom / Motion activated light (Home Mode)
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.vaskerom_motion_sensor_bevegelse
    to: "on"
    id: motion_detected
  - trigger: state
    entity_id:
      - binary_sensor.vaskerom_motion_sensor_bevegelse
    to: "off"
    id: motion_clear
    for:
      hours: 0
      minutes: 2
      seconds: 0
conditions:
  - condition: state
    entity_id: input_boolean.home_mode
    state: "on"
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - motion_detected
              - condition: state
                entity_id: sensor.dallonaveien_15a_electricity_price
                attribute: price_level
                state: LOW
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 5
              rgb_color:
                - 0
                - 249
                - 0
              brightness_pct: 100
            target:
              area_id: vaskerom
          - alias: Dim light and change color after a short time
            sequence:
              - delay:
                  hours: 0
                  minutes: 1
                  seconds: 30
              - action: light.turn_on
                metadata: {}
                data:
                  transition: 5
                  rgb_color:
                    - 0
                    - 249
                    - 0
                  brightness_pct: 50
                target:
                  area_id:
                    - vaskerom
            enabled: false
        alias: Turn on lights when motion is detected and price is LOW
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - motion_detected
              - condition: state
                entity_id: sensor.dallonaveien_15a_electricity_price
                attribute: price_level
                state: NORMAL
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 5
              rgb_color:
                - 255
                - 251
                - 0
              brightness_pct: 100
            target:
              area_id: vaskerom
          - alias: Dim light and change color after a short time
            sequence:
              - delay:
                  hours: 0
                  minutes: 1
                  seconds: 30
              - action: light.turn_on
                metadata: {}
                data:
                  transition: 5
                  rgb_color:
                    - 0
                    - 249
                    - 0
                  brightness_pct: 50
                target:
                  area_id:
                    - vaskerom
            enabled: false
        alias: Turn on lights when motion is detected and price is NORMAL
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - motion_detected
              - condition: state
                entity_id: sensor.dallonaveien_15a_electricity_price
                attribute: price_level
                state: HIGH
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 5
              rgb_color:
                - 255
                - 38
                - 0
              brightness_pct: 100
            target:
              area_id: vaskerom
          - alias: Dim light and change color after a short time
            sequence:
              - delay:
                  hours: 0
                  minutes: 1
                  seconds: 30
              - action: light.turn_on
                metadata: {}
                data:
                  transition: 5
                  rgb_color:
                    - 0
                    - 249
                    - 0
                  brightness_pct: 50
                target:
                  area_id:
                    - vaskerom
            enabled: false
        alias: Turn on lights when motion is detected and price is HIGH
      - conditions:
          - condition: trigger
            id:
              - motion_clear
        sequence:
          - action: light.turn_off
            metadata: {}
            data:
              transition: 5
            target:
              area_id: vaskerom
        alias: Turn off lights when motion is clear
mode: restart
